### ISSUE TITLE
error while executing ng serve

### ISSUE THREAD

**Issue by distributev** [distributev/rundeck-prototype#1]
![image](https://user-images.githubusercontent.com/19224635/41412840-91f742a8-6fe1-11e8-9b60-742e51a8cd3d.png)

**Comment by nikitacherevko** [comment]
My bad, I've added missed package file. Could you please pull the latest changes and try again?
If it doesn't help please let me know: then you need to load dev dependencies using the command 
`npm i --only=dev
`

**Comment by distributev** [comment]
why package-lock.json was added to the source code repository?
package-lock.json will be generated automatically when I run npm install so there is no need to add this file to repository

by the way I noticed now that the npm install command is missing from the help instructions - this is probably why I got the error - please remove package-lock.json from repository and add npm install step to https://github.com/distributev/rundeck-prototype/blob/master/HELP.md

**Comment by nikitacherevko** [comment]
@distributev yes, I've missed npm install command. Will add it

regarding package-lock.json... official documentation says this file is intended to be pushed into git
https://docs.npmjs.com/files/package-lock.json
